# Generated by Django 4.2.1 on 2026-09-27 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=5)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='reservas',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='estadoacceso',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=5),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='cancha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='duracion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=5),
        ),
    ]
