# Generated by Django 4.2.1 on 2026-09-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_perfiladministrador_delete_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cancha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='duracion',
            field=models.PositiveIntegerField(),
        ),
    ]
