# Generated by Django 4.2.1 on 2026-09-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_reservas_cancha_alter_reservas_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='comprobante_pago',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
