# Generated by Django 4.2.1 on 2026-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_reservas_comprobante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiladministrador',
            name='indicativo_pais',
            field=models.CharField(choices=[('+57', 'Colombia (+57)'), ('+1', 'Estados Unidos / Canadá (+1)'), ('+52', 'México (+52)'), ('+54', 'Argentina (+54)'), ('+55', 'Brasil (+55)'), ('+56', 'Chile (+56)'), ('+51', 'Perú (+51)'), ('+593', 'Ecuador (+593)'), ('+58', 'Venezuela (+58)'), ('+507', 'Panamá (+507)'), ('+506', 'Costa Rica (+506)'), ('+502', 'Guatemala (+502)'), ('+503', 'El Salvador (+503)'), ('+504', 'Honduras (+504)'), ('+505', 'Nicaragua (+505)'), ('+591', 'Bolivia (+591)'), ('+595', 'Paraguay (+595)'), ('+598', 'Uruguay (+598)'), ('+34', 'España (+34)'), ('+44', 'Reino Unido (+44)'), ('+33', 'Francia (+33)'), ('+49', 'Alemania (+49)'), ('+39', 'Italia (+39)')], default='+57', max_length=6),
        ),
        migrations.AddField(
            model_name='perfiladministrador',
            name='primer_apellido',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfiladministrador',
            name='primer_nombre',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfiladministrador',
            name='segundo_apellido',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfiladministrador',
            name='segundo_nombre',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='indicativo_pais',
            field=models.CharField(choices=[('+57', 'Colombia (+57)'), ('+1', 'Estados Unidos / Canadá (+1)'), ('+52', 'México (+52)'), ('+54', 'Argentina (+54)'), ('+55', 'Brasil (+55)'), ('+56', 'Chile (+56)'), ('+51', 'Perú (+51)'), ('+593', 'Ecuador (+593)'), ('+58', 'Venezuela (+58)'), ('+507', 'Panamá (+507)'), ('+506', 'Costa Rica (+506)'), ('+502', 'Guatemala (+502)'), ('+503', 'El Salvador (+503)'), ('+504', 'Honduras (+504)'), ('+505', 'Nicaragua (+505)'), ('+591', 'Bolivia (+591)'), ('+595', 'Paraguay (+595)'), ('+598', 'Uruguay (+598)'), ('+34', 'España (+34)'), ('+44', 'Reino Unido (+44)'), ('+33', 'Francia (+33)'), ('+49', 'Alemania (+49)'), ('+39', 'Italia (+39)')], default='+57', max_length=6),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='primer_apellido',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='primer_nombre',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='segundo_apellido',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='segundo_nombre',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reservas',
            name='indicativo_pais',
            field=models.CharField(choices=[('+57', 'Colombia (+57)'), ('+1', 'Estados Unidos / Canadá (+1)'), ('+52', 'México (+52)'), ('+54', 'Argentina (+54)'), ('+55', 'Brasil (+55)'), ('+56', 'Chile (+56)'), ('+51', 'Perú (+51)'), ('+593', 'Ecuador (+593)'), ('+58', 'Venezuela (+58)'), ('+507', 'Panamá (+507)'), ('+506', 'Costa Rica (+506)'), ('+502', 'Guatemala (+502)'), ('+503', 'El Salvador (+503)'), ('+504', 'Honduras (+504)'), ('+505', 'Nicaragua (+505)'), ('+591', 'Bolivia (+591)'), ('+595', 'Paraguay (+595)'), ('+598', 'Uruguay (+598)'), ('+34', 'España (+34)'), ('+44', 'Reino Unido (+44)'), ('+33', 'Francia (+33)'), ('+49', 'Alemania (+49)'), ('+39', 'Italia (+39)')], default='+57', max_length=6),
        ),
        migrations.AlterField(
            model_name='perfiladministrador',
            name='celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='perfiladministrador',
            name='documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='perfiladministrador',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], max_length=5),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], max_length=5),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='cel',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], max_length=5),
        ),
        migrations.AddConstraint(
            model_name='perfiladministrador',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'documento'), name='uq_admin_tipo_documento'),
        ),
        migrations.AddConstraint(
            model_name='perfilcliente',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'documento'), name='uq_cliente_tipo_documento'),
        ),
    ]
